!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Q0: 0.01
  Q1: 0.01
  Q2: 0.01
  Q3: 0.01
  Q4: 0.01
  Q5: 0.01
  Q6: 0.01
  Q7: 0.01
  Q8: 0.01
  Q9: 0.01
  R0: 1000.0
  R1: 1000.0
  R2: 1000.0
  R3: 1000.0
  R4: 1000.0
  R5: 1000.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Q0: 0.01
      Q1: 0.01
      Q2: 0.01
      Q3: 0.01
      Q4: 0.01
      Q5: 0.01
      Q6: 0.01
      Q7: 0.01
      Q8: 0.01
      Q9: 0.01
      R0: 1000.0
      R1: 1000.0
      R2: 1000.0
      R3: 1000.0
      R4: 1000.0
      R5: 1000.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
state: []
